---

- name: Win_ping - ping windows hosts
  gather_facts: false
  ignore_errors: false
  become: false
  hosts: immersion_pods
  roles:
    - test # current tasks that are being run are under the test role. 