---
- name: Send notification
  debug:
    msg: "Sending notification with message: {{ body_message }} and urgency: {{ urgency }}"
  # Replace with actual notification task, e.g., sending an email or a message to a monitoring system