---
# Close discord

- name: Read and parse existing MediaJson
  slurp:
    src: '{{ playbook_dir }}/files/mediaEngine.json'
  register: discord_json
  ignore_errors: true


- name: Parse JSON content
  set_fact:
    discord_settings: "{{ discord_json['content'] | b64decode | from_json }}"


- name: Check if conditions are met
  set_fact:
    attenuation_is_zero: true
    automatic_input_sensitivty: true
    vad_use_krisp_is_true: true
    hardware_h264_is_false: true
  when:
    - parsed_json.default.attenuation == 0
    - parsed_json.default.modeOptions.vadUseKrisp == true
    - parsed_json.default.modeOptions.autoThreshold == true
    - parsed_json.default.hardwareH264 == false